# **XII) ARIMA GARCH Analysis**


1. [**Environment & Config**](#1-env--conf)
2. [**Automated Model Selection**](#2-model--select)
3. [**Performance Benchmarking**](#3-performance)
4. [**Does adding the MPE improve the ARIMA?**](#4-arimax-mpe)

### **1) Environment & Config** <a id="1-env--conf"></a>

In [1]:
import numpy as np
import pandas as pd
import warnings
from statsmodels.tsa.arima.model import ARIMA
from scipy import stats
from statsmodels.tools.sm_exceptions import ConvergenceWarning
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

warnings.simplefilter("ignore", ConvergenceWarning)

DATA_PATH = "data/All_Data_Weekly_transformed.csv"
target = "btc_ret"

FOLDS = [
    dict(name="fold1", 
        train=("2014-09-19", "2020-03-27"),
        val=("2020-04-03", "2020-12-25"),    
        test=("2021-01-01", "2021-12-31") 
        ),
    dict(name="fold2",
        train=("2014-09-19", "2021-03-26"),
        val=("2021-04-02", "2021-12-31"),   
        test=("2022-01-07", "2022-12-30") 
    ),
    dict(name="fold3", 
         train=("2014-09-19","2022-03-25"), 
         val=("2022-04-01","2022-12-30"), 
         test=("2023-01-06","2023-12-29")
        ),
    dict(name="fold4", 
         train=("2014-09-19", "2023-03-31"),   
         val=("2023-04-07", "2023-12-29"),     
         test=("2024-01-05", "2025-04-04")    
        ),
]

df = pd.read_csv(DATA_PATH, parse_dates=["date"]).set_index("date").sort_index()
y = df[target].astype(float)

### **2) Automated Model Selection** <a id="2-model--select"></a>

In [2]:
def _clean(arr):
    arr = np.asarray(arr, dtype=float)
    return arr[np.isfinite(arr)]

def select_order_aic(y_train, pmax=6, qmax=6, d=0):
    """
    Fast selection: fit each candidate once on training data and pick the lowest AIC.
    """
    y_train = _clean(y_train)
    best_order, best_aic = None, np.inf

    for p in range(pmax + 1):
        for q in range(qmax + 1):
            if p == 0 and q == 0:
                continue
            order = (p, d, q)
            try:
                res = ARIMA(
                    y_train,
                    order=order,
                    enforce_stationarity=False,
                    enforce_invertibility=False,
                ).fit(method_kwargs={"maxiter": 200})
                if np.isfinite(res.aic) and res.aic < best_aic:
                    best_aic, best_order = res.aic, order
            except Exception:
                pass

    if best_order is None:
        best_order = (1, d, 1)  # safe fallback
    return best_order

def rolling_1step_preds(y_init, y_future, order):
    """
    Fit once on y_init, then 1-step forecasts while appending realized values (no refit).
    """
    y_init = _clean(y_init)
    y_future = _clean(y_future)

    res = ARIMA(
        y_init,
        order=order,
        enforce_stationarity=False,
        enforce_invertibility=False,
    ).fit(method_kwargs={"maxiter": 200})

    preds = np.empty(len(y_future), dtype=float)
    for i, obs in enumerate(y_future):
        preds[i] = float(res.forecast(1)[0])
        res = res.append([obs], refit=False)
    return preds

### **3) Performance Benchmarking** <a id="3-performance"></a>

In [3]:
# New code combining AR(1), AR(2), and ARIMA
# We also save ARIMA outputs for DM test

import os
os.makedirs("data/arima_outputs", exist_ok=True)

rows = []

for f in FOLDS:
    tr0, tr1 = f["train"]
    va0, va1 = f["val"]
    te0, te1 = f["test"]

    y_tr = y.loc[tr0:tr1].to_numpy()
    y_te = y.loc[te0:te1].dropna().to_numpy()
    y_tv = y.loc[tr0:va1].to_numpy()

    # ARIMA
    order = select_order_aic(y_tr, pmax=3, qmax=3, d=0)
    preds_arima = rolling_1step_preds(y_tv, y_te, order)

    # Save ARIMA predictions for DM test
    np.save(f"data/arima_outputs/{f['name']}_y_true.npy", y_te)
    np.save(f"data/arima_outputs/{f['name']}_y_pred_arima.npy", preds_arima)

    rmse_arima = float(np.sqrt(mean_squared_error(y_te, preds_arima)))
    mae_arima  = float(mean_absolute_error(y_te, preds_arima))
    r2_arima   = float(r2_score(y_te, preds_arima))

    # AR(1)
    preds_ar1 = rolling_1step_preds(y_tv, y_te, order=(1,0,0))

    rmse_ar1 = float(np.sqrt(mean_squared_error(y_te, preds_ar1)))
    mae_ar1  = float(mean_absolute_error(y_te, preds_ar1))
    r2_ar1   = float(r2_score(y_te, preds_ar1))

    # AR(2)
    preds_ar2 = rolling_1step_preds(y_tv, y_te, order=(2,0,0))

    rmse_ar2 = float(np.sqrt(mean_squared_error(y_te, preds_ar2)))
    mae_ar2  = float(mean_absolute_error(y_te, preds_ar2))
    r2_ar2   = float(r2_score(y_te, preds_ar2))

    # Store everything
    rows.append({
        "fold": f["name"],

        "ARIMA_RMSE": rmse_arima,
        "ARIMA_MAE": mae_arima,
        "ARIMA_R2": r2_arima,
        "ARIMA_order": order,

        "AR1_RMSE": rmse_ar1,
        "AR1_MAE": mae_ar1,
        "AR1_R2": r2_ar1,

        "AR2_RMSE": rmse_ar2,
        "AR2_MAE": mae_ar2,
        "AR2_R2": r2_ar2,
    })

    print(f'{f["name"]} | ARIMA RMSE={rmse_arima:.6f} | AR(1) RMSE={rmse_ar1:.6f} | AR(2) RMSE={rmse_ar2:.6f}')

results = pd.DataFrame(rows).set_index("fold").sort_index()
display(results)
print("Mean RMSE:", results["ARIMA_RMSE"].mean())

fold1 | ARIMA RMSE=0.129452 | AR(1) RMSE=0.111463 | AR(2) RMSE=0.113239
fold2 | ARIMA RMSE=0.087573 | AR(1) RMSE=0.086359 | AR(2) RMSE=0.086411
fold3 | ARIMA RMSE=0.067069 | AR(1) RMSE=0.067147 | AR(2) RMSE=0.067477
fold4 | ARIMA RMSE=0.065103 | AR(1) RMSE=0.065154 | AR(2) RMSE=0.065567

,ARIMA_RMSE,ARIMA_MAE,ARIMA_R2,ARIMA_order,AR1_RMSE,AR1_MAE,AR1_R2,AR2_RMSE,AR2_MAE,AR2_R2
fold,,,,,,,,,,
fold1,0.129452,0.106662,-0.341631,"(2, 0, 2)",0.111463,0.087600,0.005340,0.113239,0.089722,-0.026617
fold2,0.087573,0.062283,-0.190383,"(2, 0, 2)",0.086359,0.060618,-0.157593,0.086411,0.060951,-0.159000
fold3,0.067069,0.047679,-0.019639,"(0, 0, 1)",0.067147,0.047609,-0.022008,0.067477,0.047907,-0.032063
fold4,0.065103,0.049696,0.009598,"(0, 0, 1)",0.065154,0.049724,0.008032,0.065567,0.050233,-0.004583

Mean RMSE: 0.08729942780708905

In [4]:
n = len(results)
mean_val = results.mean(numeric_only=True)
std_val = results.std(numeric_only=True)
se_val = std_val / np.sqrt(n)

results.loc["TOTAL (Mean)"] = mean_val
results.loc["TOTAL (SE)"] = se_val

display(results)

,ARIMA_RMSE,ARIMA_MAE,ARIMA_R2,ARIMA_order,AR1_RMSE,AR1_MAE,AR1_R2,AR2_RMSE,AR2_MAE,AR2_R2
fold,,,,,,,,,,
fold1,0.129452,0.106662,-0.341631,"(2, 0, 2)",0.111463,0.087600,0.005340,0.113239,0.089722,-0.026617
fold2,0.087573,0.062283,-0.190383,"(2, 0, 2)",0.086359,0.060618,-0.157593,0.086411,0.060951,-0.159000
fold3,0.067069,0.047679,-0.019639,"(0, 0, 1)",0.067147,0.047609,-0.022008,0.067477,0.047907,-0.032063
fold4,0.065103,0.049696,0.009598,"(0, 0, 1)",0.065154,0.049724,0.008032,0.065567,0.050233,-0.004583
TOTAL (Mean),0.087299,0.066580,-0.135514,NaN,0.082531,0.061388,-0.041557,0.083174,0.062203,-0.055566
TOTAL (SE),0.014941,0.013746,0.081639,NaN,0.010764,0.009190,0.039269,0.011071,0.009603,0.034986

### **4) Does adding the MPE improve the ARIMA?** <a id="4-arimax-mpe"></a>


**Design.** The section-3 pipeline is run twice — same AIC-selected $(p,d,q)$, same estimation
window, same rolling one-step-ahead forecasts, same test weeks — differing only by
$\text{mp\_exp}_{t-1}$ as an exogenous regressor. The one-week lag keeps the forecast valid: the
regressor for week $t$ must be known at the end of week $t-1$.

**Evaluation is pooled.** The four test windows are disjoint and consecutive, so their forecasts stack
into one out-of-sample series of 215 weeks — enough power to answer whether the MPE helps *overall*,
which no single ~50-week window can. Only the pooled comparison is reported.

**Test.** Clark-West, not Diebold-Mariano: the ARIMA is *nested* inside the ARIMAX, and DM is biased
against the larger model in that case (under the null the extra parameter adds pure estimation
noise). CW corrects this bias. DM is printed alongside for comparability with the LSTM table.

In [5]:
# does adding the MPE improve the ARIMA?
# Nested comparison, one regressor apart; forecasts pooled across the 4 folds.

# Regressor for week t must be known at t-1 (section 3 forecasts unshifted y).
panel = pd.concat([y.rename("y"), df["mp_exp"].astype(float).shift(1).rename("x")], axis=1)

def rolling_1step_preds_exog(y_init, x_init, y_future, x_future, order):
    """Section-3 `rolling_1step_preds` with an exogenous regressor."""
    res = ARIMA(np.asarray(y_init, float), exog=np.asarray(x_init, float).reshape(-1, 1),
                order=order, enforce_stationarity=False,
                enforce_invertibility=False).fit(method_kwargs={"maxiter": 200})
    preds = np.empty(len(y_future), float)
    for i, obs in enumerate(y_future):
        xf = np.asarray([[x_future[i]]], float)
        preds[i] = float(res.forecast(1, exog=xf)[0])
        res = res.append([obs], exog=xf, refit=False)
    return preds


# Folds are forecast separately (each has its own AIC order and estimation window),
# then stacked: only the pooled series is reported.
Y_all, P_base_all, P_mpe_all = [], [], []

for f in FOLDS:
    tr0, tr1 = f["train"]; va0, va1 = f["val"]; te0, te1 = f["test"]
    tv = panel.loc[tr0:va1].dropna()      # aligned so the two models see identical rows
    te = panel.loc[te0:te1].dropna()
    order = select_order_aic(y.loc[tr0:tr1].to_numpy(), pmax=3, qmax=3, d=0)

    p_base = rolling_1step_preds(tv["y"].to_numpy(), te["y"].to_numpy(), order)
    p_mpe = rolling_1step_preds_exog(tv["y"].to_numpy(), tv["x"].to_numpy(),
                                     te["y"].to_numpy(), te["x"].to_numpy(), order)

    Y_all.append(te["y"].to_numpy()); P_base_all.append(p_base); P_mpe_all.append(p_mpe)

Y = np.concatenate(Y_all); P_BASE = np.concatenate(P_base_all); P_MPE = np.concatenate(P_mpe_all)
e_base, e_mpe = Y - P_BASE, Y - P_MPE

rmse_base = float(np.sqrt(mean_squared_error(Y, P_BASE)))
rmse_mpe = float(np.sqrt(mean_squared_error(Y, P_MPE)))
r2_os = 100 * (1 - np.sum(e_mpe ** 2) / np.sum(e_base ** 2))

# DM: d = e_base^2 - e_mpe^2, so DM > 0 favours the ARIMAX. Biased here (nested).
d = e_base ** 2 - e_mpe ** 2
dm_stat = d.mean() / np.sqrt(d.var(ddof=1) / len(d))
dm_p = 2 * (1 - stats.norm.cdf(abs(dm_stat)))

# Clark-West: the (P_BASE - P_MPE)^2 term removes the estimation noise the extra
# parameter necessarily adds under the null. One-sided, H1: ARIMAX better.
f_cw = e_base ** 2 - e_mpe ** 2 + (P_BASE - P_MPE) ** 2
cw_stat = f_cw.mean() / np.sqrt(f_cw.var(ddof=1) / len(f_cw))
cw_p = 1 - stats.norm.cdf(cw_stat)

# Readable table (same data as the LaTeX below) 
_pooled = pd.DataFrame([{
    "N weeks": len(Y), "ARIMA RMSE": rmse_base, "ARIMAX RMSE": rmse_mpe,
    "Gain %": 100 * (rmse_base - rmse_mpe) / rmse_base, "OOS R2 %": r2_os,
    "CW stat": cw_stat, "CW p": cw_p, "DM p": dm_p}])
print("Pooled out-of-sample comparison (4 folds stacked):")
display(_pooled.style.hide(axis="index").format({
    "ARIMA RMSE": "{:.4f}", "ARIMAX RMSE": "{:.4f}", "Gain %": "{:+.2f}",
    "OOS R2 %": "{:+.2f}", "CW stat": "{:.3f}", "CW p": "{:.4f}", "DM p": "{:.4f}"}))


# LaTeX table
def _stars(p):
    return "^{***}" if p < 0.01 else "^{**}" if p < 0.05 else "^{*}" if p < 0.10 else ""

latex = rf"""\begin{{table}}[H]
\centering
\caption{{Does Adding the MPE Improve the ARIMA?}}
\label{{tab:arimax_mpe}}
\begin{{small}}
\caption*{{\small \textbf{{Notes:}} Nested one-step-ahead forecast comparison over the
{len(Y)} pooled out-of-sample weeks. Both models share the same AIC-selected order,
estimation window and rolling forecast scheme, and differ only by the lagged MPE index
$\text{{mp\_exp}}_{{t-1}}$ as an exogenous regressor; the one-week lag makes the regressor
observable at the forecast origin. The four disjoint test windows are stacked into a single
series, as individual windows of about 50 weeks are too short to be informative. Gain is the
percentage reduction in RMSE and $R^2_{{OS}}$ is computed against the ARIMA benchmark.
Clark--West is the appropriate test for nested models, where Diebold--Mariano is biased against
the larger model; it is one-sided against $H_1$: the ARIMAX forecasts better. Test statistics
are reported with $p$-values in parentheses.
$^{{*}}p<0.10$, $^{{**}}p<0.05$, $^{{***}}p<0.01$.}}
\end{{small}}
\resizebox{{0.8\textwidth}}{{!}}{{%
\begin{{tabular}}{{l cccc}}
\toprule
& RMSE ARIMA & RMSE ARIMAX & Gain (\%) & $R^2_{{OS}}$ (\%) \\
\midrule
\textit{{Forecast accuracy}} & {rmse_base:.4f} & {rmse_mpe:.4f} & {100 * (rmse_base - rmse_mpe) / rmse_base:+.2f} & {r2_os:+.2f} \\
\midrule
& \multicolumn{{2}}{{c}}{{Clark--West}} & \multicolumn{{2}}{{c}}{{Diebold--Mariano}} \\
\midrule
\textit{{Equal predictive accuracy}} & \multicolumn{{2}}{{c}}{{${cw_stat:.3f}{_stars(cw_p)}$ ({cw_p:.4f})}} & \multicolumn{{2}}{{c}}{{${dm_stat:.3f}$ ({dm_p:.4f})}} \\
\bottomrule
\end{{tabular}}}}
\end{{table}}"""

print(latex)

Pooled out-of-sample comparison (4 folds stacked):

\begin{table}[H]
\centering
\caption{Does Adding the MPE Improve the ARIMA?}
\label{tab:arimax_mpe}
\begin{small}
\caption*{\small \textbf{Notes:} Nested one-step-ahead forecast comparison over the
215 pooled out-of-sample weeks. Both models share the same AIC-selected order,
estimation window and rolling forecast scheme, and differ only by the lagged MPE index
$\text{mp\_exp}_{t-1}$ as an exogenous regressor; the one-week lag makes the regressor
observable at the forecast origin. The four disjoint test windows are stacked into a single
series, as individual windows of about 50 weeks are too short to be informative. Gain is the
percentage reduction in RMSE and $R^2_{OS}$ is computed against the ARIMA benchmark.
Clark--West is the appropriate test for nested models, where Diebold--Mariano is biased against
the larger model; it is one-sided against $H_1$: the ARIMAX forecasts better. Test statistics
are reported with $p$-values in parentheses.
$^{*}p<0.10$, $^{**}p<0.05$, $^{***}p<0.01$.}
\end{small}
\resizebox{0.8\textwidth}{!}{%
\begin{tabular}{l cccc}
\toprule
& RMSE ARIMA & RMSE ARIMAX & Gain (\%) & $R^2_{OS}$ (\%) \\
\midrule
\textit{Forecast accuracy} & 0.0902 & 0.0895 & +0.82 & +1.62 \\
\midrule
& \multicolumn{2}{c}{Clark--West} & \multicolumn{2}{c}{Diebold--Mariano} \\
\midrule
\textit{Equal predictive accuracy} & \multicolumn{2}{c}{$2.071^{**}$ (0.0192)} & \multicolumn{2}{c}{$0.462$ (0.6439)} \\
\bottomrule
\end{tabular}}
\end{table}